import { Router, type IRouter } from "express";
import { eq } from "drizzle-orm";
import {
  db,
  projects,
  entities,
  rules,
  players,
  assets,
} from "@workspace/db";
import { schemas } from "@workspace/api-zod";
import { complete } from "../lib/aiRouter";

const router: IRouter = Router();

router.post(
  "/projects/:projectId/export/:kind",
  async (req, res): Promise<void> => {
    const params = schemas.GenerateExportParams.safeParse(req.params);
    if (!params.success) {
      res.status(400).json({ error: params.error.message });
      return;
    }
    const projectId = params.data.projectId;
    const kind = params.data.kind;
    const [project] = await db
      .select()
      .from(projects)
      .where(eq(projects.id, projectId));
    if (!project) {
      res.status(404).json({ error: "Project not found" });
      return;
    }
    const [es, rs, ps, as] = await Promise.all([
      db.select().from(entities).where(eq(entities.projectId, projectId)),
      db.select().from(rules).where(eq(rules.projectId, projectId)),
      db.select().from(players).where(eq(players.projectId, projectId)),
      db.select().from(assets).where(eq(assets.projectId, projectId)),
    ]);

    const slug = project.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");

    if (kind === "tts-json") {
      const obj = {
        SaveName: project.name,
        GameMode: "Custom",
        Description: project.description ?? "",
        ObjectStates: es.map((e, i) => ({
          Name: "Card",
          Nickname: e.name,
          Description: e.description ?? "",
          Transform: { posX: i * 2, posY: 1, posZ: 0 },
        })),
      };
      res.json(
        schemas.GenerateExportResponse.parse({
          kind,
          contentType: "application/json",
          filename: `${slug}-tts.json`,
          content: JSON.stringify(obj, null, 2),
        }),
      );
      return;
    }

    if (kind === "rulebook-md") {
      const lines: string[] = [];
      lines.push(`# ${project.name}`);
      if (project.description) lines.push(`\n${project.description}\n`);
      lines.push(`\n**Game type:** ${project.gameType ?? "—"}`);
      lines.push(`**Genre:** ${project.genre ?? "—"}`);
      lines.push(`**Players:** ${project.playerCount ?? "—"}`);
      lines.push(`**Duration:** ${project.targetDuration ?? "—"}\n`);
      lines.push(`## Components\n`);
      for (const e of es) {
        lines.push(`- **${e.name}** _(${e.type})_${e.description ? ` — ${e.description}` : ""}`);
      }
      lines.push(`\n## Player Archetypes\n`);
      for (const p of ps) {
        lines.push(
          `- **${p.name}**${p.role ? ` _(${p.role})_` : ""}${p.description ? ` — ${p.description}` : ""}`,
        );
      }
      lines.push(`\n## Rules\n`);
      const cats = Array.from(new Set(rs.map((r) => r.category ?? "Other")));
      for (const c of cats) {
        lines.push(`\n### ${c}\n`);
        for (const r of rs.filter((x) => (x.category ?? "Other") === c)) {
          lines.push(`**${r.title}**\n${r.content}\n`);
        }
      }
      lines.push(`\n---\n*Generated by GameForge*`);
      res.json(
        schemas.GenerateExportResponse.parse({
          kind,
          contentType: "text/markdown",
          filename: `${slug}-rulebook.md`,
          content: lines.join("\n"),
        }),
      );
      return;
    }

    const ctx = `Game: ${project.name}
Type: ${project.gameType ?? "—"} / ${project.genre ?? "—"}
Players: ${project.playerCount ?? "—"} | Duration: ${project.targetDuration ?? "—"}
Description: ${project.description ?? "—"}
Entities: ${es.slice(0, 12).map((e) => e.name).join(", ")}
Rules: ${rs.slice(0, 8).map((r) => r.title).join("; ")}
Archetypes: ${ps.map((p) => p.name).join(", ")}
Assets: ${as.length} cards/components`;

    let prompt = "";
    let filename = `${slug}.md`;
    if (kind === "kickstarter") {
      prompt = `Write a Kickstarter campaign page in markdown for this board game. Include sections: Hook (1-paragraph pitch), The Story (2-3 paragraphs), How To Play (5-step bullet list), What's In The Box (bullets), Stretch Goals (3 ideas), Reward Tiers (4 tiers from $25 to $200), Designer Note. Be punchy, sincere, and specific.

${ctx}`;
      filename = `${slug}-kickstarter.md`;
    } else if (kind === "sell-sheet") {
      prompt = `Write a publisher sell-sheet in markdown for this game. One page only. Include: Title, Tagline, At-A-Glance (players/time/age/complexity), 1-paragraph pitch, 3 unique selling points, 3 differentiators vs comparable titles, Designer Bio placeholder. Be tight and confident.

${ctx}`;
      filename = `${slug}-sell-sheet.md`;
    } else if (kind === "press-kit") {
      prompt = `Write a press kit in markdown for this board game. Include: Headline, Boilerplate (3 sentences), Key Facts list, Press Quotes section (placeholder), Available Imagery (list), Contact (placeholder), FAQ (5 likely questions and answers).

${ctx}`;
      filename = `${slug}-press-kit.md`;
    } else {
      res.status(400).json({ error: "Unsupported export kind" });
      return;
    }

    try {
      const text = await complete(req, { prompt, maxTokens: 3000 });
      res.json(
        schemas.GenerateExportResponse.parse({
          kind,
          contentType: "text/markdown",
          filename,
          content: text,
        }),
      );
    } catch (err) {
      req.log.error({ err }, "export generation failed");
      res.status(500).json({ error: "Export generation failed" });
    }
  },
);

export default router;
