// Extracted from ontology.tsx — canonical component documentation and property glossary
// Shared across component-graph.tsx, component-library.tsx, and assets-entities.tsx

export type ComponentDoc = {
  color: string;
  border: string;
  bg: string;
  badge: string;
  hex: string;
  icon: string;
  tagline: string;
  what: string;
  ideas: string[];
  properties: { name: string; type: string; note: string }[];
  designTip: string;
};

export type GlossaryEntry = {
  name: string;
  dataType: "number" | "string" | "boolean" | "enum" | "text";
  appliesTo: string[];
  description: string;
  rulesInteraction: string;
  example: string;
};

export const COMPONENT_DOCS: Record<string, ComponentDoc> = {
  Card: {
    color: "text-violet-400",
    border: "border-violet-500/30",
    bg: "bg-violet-500/5",
    badge: "bg-violet-500/20 text-violet-400 border-violet-500/30",
    hex: "#7c3aed",
    icon: "🃏",
    tagline: "Individual playable cards drawn from a hand or deck.",
    what: "Cards are the primary interaction medium in card-driven games. Each card is a discrete unit of choice — playing, holding, or discarding it creates tension, planning, and hand management decisions. The composition of your hand at any moment defines your options.",
    ideas: [
      "Action Card — Play for an immediate effect or bonus",
      "Item Card — Equip for persistent stat boosts",
      "Spell Card — One-time powerful effect, often costly",
      "Encounter Card — Drawn from a deck, reactive surprise",
      "Quest Card — Long-term objective with staged rewards",
      "Treasure Card — Loot with varying rarity and effects",
      "Attack / Defense Card — Played in combat as reactions",
    ],
    properties: [
      { name: "cost", type: "number", note: "Resources or action points to play this card" },
      { name: "power", type: "number", note: "Offensive value in combat resolution" },
      { name: "defense", type: "number", note: "Damage mitigation when played defensively" },
      { name: "effect_type", type: "enum", note: "buff / debuff / damage / heal / draw / discard" },
      { name: "trigger", type: "string", note: "Condition under which the effect fires" },
      { name: "rarity", type: "enum", note: "common / uncommon / rare / legendary" },
      { name: "hand_cost", type: "number", note: "Additional cards discarded to play this" },
    ],
    designTip:
      "Cards with dual modes (play for effect A or discard for effect B) multiply decisions without adding rules complexity. Control how many copies exist per deck — scarcity drives tension.",
  },
  Deck: {
    color: "text-indigo-400",
    border: "border-indigo-500/30",
    bg: "bg-indigo-500/5",
    badge: "bg-indigo-500/20 text-indigo-400 border-indigo-500/30",
    hex: "#4f46e5",
    icon: "📦",
    tagline: "An ordered or shuffled collection of cards players draw from.",
    what: "Decks are the supply source for card interactions. They create uncertainty (what's coming next?), pacing, and depletion tension. A thinning deck or a freshly shuffled one each produce distinct strategic feelings — the state of the deck IS information.",
    ideas: [
      "Action Deck — Core decision cards for the active player",
      "Event Deck — World events triggered each round",
      "Encounter Deck — Enemies or challenges drawn on entry",
      "Spell / Magic Deck — Drawn by caster characters only",
      "Loot Deck — Rewards drawn after clearing a room",
      "Market Deck — Purchasable upgrades available each turn",
    ],
    properties: [
      { name: "size", type: "number", note: "Total cards at game start" },
      { name: "cards_per_draw", type: "number", note: "Cards drawn per action" },
      { name: "shuffle_when_empty", type: "boolean", note: "Reshuffle discard pile to refill?" },
      { name: "shared", type: "boolean", note: "One deck for all vs. per-player deck?" },
      { name: "visible_top", type: "boolean", note: "Top card visible to all players?" },
      { name: "discard_visible", type: "boolean", note: "Discard pile face-up and inspectable?" },
    ],
    designTip:
      "Deck thickness controls information density. Thin decks (10–15 cards) cycle fast and feel predictable — ideal for engine-builders. Thick decks (40+) feel like a lottery — right for randomness-heavy themes.",
  },
  Token: {
    color: "text-amber-400",
    border: "border-amber-500/30",
    bg: "bg-amber-500/5",
    badge: "bg-amber-500/20 text-amber-400 border-amber-500/30",
    hex: "#d97706",
    icon: "🪙",
    tagline: "Physical markers tracking resources, status, or quantities on the board.",
    what: "Tokens are the economy's heartbeat — they track health, currency, influence, and any countable game state. The act of gaining and losing tokens is often the most tactile and satisfying core loop. Supply scarcity (running out of tokens) creates natural hard limits.",
    ideas: [
      "Health / Hit Points — Damage tracker per unit",
      "Gold / Coin — Spend on actions or purchases",
      "Victory Points — Accumulate for end-game scoring",
      "Status Marker — Poisoned, Burning, Stunned",
      "Influence Chip — Political or social power",
      "Food / Supply — Upkeep consumed each round",
      "Action Token — Placed to mark a used action",
    ],
    properties: [
      { name: "quantity", type: "number", note: "Total supply in the game box" },
      { name: "max_stack", type: "number", note: "Max per player or per space" },
      { name: "per_player", type: "boolean", note: "Each player has own supply?" },
      { name: "tradeable", type: "boolean", note: "Can players exchange freely?" },
      { name: "stackable", type: "boolean", note: "Can multiples share one space?" },
      { name: "value", type: "number", note: "Point or trade value per token" },
    ],
    designTip:
      "Keep tokens physically distinct — different shapes or colors prevent confusion during high-tension plays. Soft caps (max 10 gold) create interesting spend pressure before the cap hits.",
  },
  Die: {
    color: "text-red-400",
    border: "border-red-500/30",
    bg: "bg-red-500/5",
    badge: "bg-red-500/20 text-red-400 border-red-500/30",
    hex: "#dc2626",
    icon: "🎲",
    tagline: "Randomizers that introduce variance and drama into key decisions.",
    what: "Dice add drama and tension. The best dice mechanics give players agency over the result — rerolls, modifiers, or choosing which result to apply — so luck feels like something you can influence, not something that simply happens to you.",
    ideas: [
      "Combat Die — Determines hit and damage in battles",
      "Action Die — Selected each round to power specific moves",
      "Event Die — Triggers random world events on a roll",
      "Skill Die — Rolled against a difficulty threshold",
      "Custom Symbol Die — Symbols mapped to unique effects",
      "Fate Die — Modifies luck or narrative outcome",
    ],
    properties: [
      { name: "faces", type: "number", note: "Number of sides (d4, d6, d8, d12, d20…)" },
      { name: "modifier", type: "number", note: "Flat bonus added to every roll result" },
      { name: "reroll_count", type: "number", note: "How many rerolls are allowed per use" },
      { name: "custom_faces", type: "string", note: "Comma-separated face values or symbols" },
      { name: "exploding", type: "boolean", note: "Max roll triggers an additional roll?" },
      { name: "pool_size", type: "number", note: "How many of this die roll simultaneously" },
    ],
    designTip:
      "Mitigation beats elimination. Give players 1–2 rerolls or ±modifiers so dice feel fair without removing variance. Pure luck frustrates; managed luck thrills.",
  },
  Tile: {
    color: "text-emerald-400",
    border: "border-emerald-500/30",
    bg: "bg-emerald-500/5",
    badge: "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
    hex: "#059669",
    icon: "🗺️",
    tagline: "Modular board pieces that define terrain, layout, and spatial relationships.",
    what: "Tiles build the physical map. They define where actions happen, movement costs, adjacency rules, and which areas are accessible or contested. Modular tiles let you change the layout between sessions, multiplying replayability without new content.",
    ideas: [
      "Dungeon Room — Revealed as players explore inward",
      "Hex Terrain — Forest, Mountain, Plains, Water, Desert",
      "Map Segment — Locks into a larger puzzle layout",
      "Starting Tile — Fixed anchor for the board setup",
      "Corridor — Single-path connector between rooms",
      "Outdoor Region — Open areas with resource nodes",
    ],
    properties: [
      { name: "terrain_type", type: "enum", note: "forest / plains / water / mountain / urban / void" },
      { name: "movement_cost", type: "number", note: "Action points required to enter" },
      { name: "defense_bonus", type: "number", note: "Combat modifier added to occupant defense" },
      { name: "passable", type: "boolean", note: "Can units move through this tile?" },
      { name: "resource_yield", type: "number", note: "Resources produced per turn while occupied" },
      { name: "vision_range", type: "number", note: "Tiles visible from this position" },
      { name: "face_down", type: "boolean", note: "Starts hidden until a player explores it?" },
    ],
    designTip:
      "Two or three terrain types are usually enough. Every additional type needs a distinct strategic purpose — otherwise it's visual noise. Chokepoints (1-tile corridors) are where the best tension lives.",
  },
  Meeple: {
    color: "text-blue-400",
    border: "border-blue-500/30",
    bg: "bg-blue-500/5",
    badge: "bg-blue-500/20 text-blue-400 border-blue-500/30",
    hex: "#2563eb",
    icon: "🧩",
    tagline: "Player pawns, figures, or standees that occupy spaces and represent presence.",
    what: "Meeples define physical presence on the board. Where your meeple is determines what actions you can take, what you control, and what threatens you. Meeples turn the board into a contest of positioning and blocking.",
    ideas: [
      "Player Pawn — One per player, tracks position",
      "Worker — Placed to lock in an action (worker placement)",
      "Unit Figure — Military or exploration unit",
      "Ship / Vehicle — Transport or naval unit",
      "Creature Standee — Monster or NPC on the board",
      "Merchant — Trade-route unit that follows paths",
    ],
    properties: [
      { name: "movement", type: "number", note: "Spaces moved per movement action" },
      { name: "health", type: "number", note: "Hit points before removed from board" },
      { name: "attack", type: "number", note: "Damage dealt per combat exchange" },
      { name: "defense", type: "number", note: "Damage reduced per incoming hit" },
      { name: "unit_type", type: "enum", note: "infantry / cavalry / ranged / naval / aerial" },
      { name: "per_player", type: "boolean", note: "Each player has one? Or shared pool?" },
      { name: "blocking", type: "boolean", note: "Does it block passage for other meeples?" },
    ],
    designTip:
      "Area control is more interesting when meeples can be captured but not permanently destroyed — capture mechanics create tension without player elimination. Give each meeple type a clear strategic niche.",
  },
  Board: {
    color: "text-slate-400",
    border: "border-slate-500/30",
    bg: "bg-slate-500/5",
    badge: "bg-slate-500/20 text-slate-400 border-slate-500/30",
    hex: "#64748b",
    icon: "📋",
    tagline: "The main playing surface — the shared stage where all action takes place.",
    what: "The board is the common space all players reference and contest. It defines the macro layout, spatial rules, progress tracks, and often the win-condition display. A well-designed board communicates the entire game state at a glance from across the table.",
    ideas: [
      "Main Board — Shared world map or primary action space",
      "Player Board — Individual dashboard and component storage",
      "Reference Sheet — Quick-rules summary (non-interactive)",
      "Score Track — Victory point display around the perimeter",
      "Market Board — Shared shop available each round",
      "Combat Grid — Battle arena for tactical skirmishes",
    ],
    properties: [
      { name: "zones", type: "number", note: "Number of distinct regions or action spaces" },
      { name: "shared", type: "boolean", note: "One board for all vs. each player has one" },
      { name: "player_count_scales", type: "boolean", note: "Board size adjusts for fewer players?" },
      { name: "double_sided", type: "boolean", note: "Alternate layout on the reverse face?" },
      { name: "track_length", type: "number", note: "Spaces on a progress or score track" },
    ],
    designTip:
      "Board real estate is expensive — every space needs a reason to exist. Score tracks and status zones should be legible from across the table. Test at minimum player count to confirm the board doesn't feel empty.",
  },
  Location: {
    color: "text-cyan-400",
    border: "border-cyan-500/30",
    bg: "bg-cyan-500/5",
    badge: "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
    hex: "#0891b2",
    icon: "📍",
    tagline: "Named places, zones, or regions that entities occupy, visit, or control.",
    what: "Locations form the navigable world. They define where players can go, what resources or encounters await them there, and what's worth fighting over. Controlling key locations often drives victory conditions.",
    ideas: [
      "City — Trade hub with market and guild access",
      "Dungeon — Multi-room encounter zone",
      "Shop / Market — Purchase location for items",
      "Landmark — Special named site with unique rules",
      "Lair — Boss encounter or high-risk high-reward site",
      "Wilderness Region — Open-world exploration area",
      "Political Seat — Controls faction influence output",
    ],
    properties: [
      { name: "terrain_type", type: "enum", note: "forest / plains / water / mountain / urban" },
      { name: "capacity", type: "number", note: "Max units or players that can occupy" },
      { name: "resource_yield", type: "number", note: "Resources produced per turn while controlled" },
      { name: "defense_bonus", type: "number", note: "Combat modifier for occupying units" },
      { name: "movement_cost", type: "number", note: "Action points to enter" },
      { name: "connected_to", type: "string", note: "Adjacent location names, comma-separated" },
      { name: "control_value", type: "number", note: "Victory points for holding at game end" },
    ],
    designTip:
      "Chokepoints (1 connection in or out) generate the best tension. Make sure there's always somewhere worth going — dead-end locations with no yield go unvisited and waste board space.",
  },
  Faction: {
    color: "text-purple-400",
    border: "border-purple-500/30",
    bg: "bg-purple-500/5",
    badge: "bg-purple-500/20 text-purple-400 border-purple-500/30",
    hex: "#9333ea",
    icon: "⚔️",
    tagline: "Groups, allegiances, or power blocs with shared goals and asymmetric abilities.",
    what: "Factions define the major players or forces. They provide identity, asymmetry, and social structure — who you align with, fight, trade with, or betray. Each faction should feel strategically distinct with a clear identity sentence.",
    ideas: [
      "Guild — Professional trade organization with market perks",
      "Tribe / Clan — Military-focused with combat bonuses",
      "Nation / Empire — Resource-rich with territorial goals",
      "Shadow Syndicate — Covert operations, spy mechanics",
      "Merchant Company — Economy and trade advantages",
      "Arcane Order — Magic and knowledge-based abilities",
      "Creature Hivemind — Alien or non-human logic set",
    ],
    properties: [
      { name: "influence", type: "number", note: "Political / social power" },
      { name: "military_strength", type: "number", note: "Combat capability rating" },
      { name: "treasury", type: "number", note: "Starting gold or resource pool" },
      { name: "morale", type: "number", note: "Efficiency modifier; falls under losses" },
      { name: "territory", type: "number", note: "Starting controlled zones" },
      { name: "diplomatic_stance", type: "enum", note: "aggressive / neutral / peaceful / isolationist" },
      { name: "unique_ability", type: "string", note: "Name of this faction's special rule" },
    ],
    designTip:
      "Asymmetric factions are the backbone of replayability. Each needs a one-sentence identity: 'The Guild wins by cornering the market; the Tribe wins by eliminating rivals.' If you can't say it in one sentence, the faction needs more focus.",
  },
  Event: {
    color: "text-orange-400",
    border: "border-orange-500/30",
    bg: "bg-orange-500/5",
    badge: "bg-orange-500/20 text-orange-400 border-orange-500/30",
    hex: "#ea580c",
    icon: "⚡",
    tagline: "Triggered or random occurrences that disrupt and reshape the game state.",
    what: "Events introduce dynamic change and narrative tension. They can be random chaos, player-triggered effects, or scheduled milestones — either way they shake up the status quo and create memorable turning points in a session.",
    ideas: [
      "Natural Disaster — Plague, Earthquake, Famine",
      "Trade Boom — Bonus resources for specific locations",
      "Political Upheaval — Shift diplomatic stances",
      "Bandit Raid — Random threat hitting exposed players",
      "Season Change — Winter shortage, summer harvest",
      "Betrayal — One player activates a traitor mechanic",
      "Discovery — New tile or location revealed to all",
    ],
    properties: [
      { name: "frequency", type: "enum", note: "once / rare / uncommon / every_round" },
      { name: "severity", type: "number", note: "1–10 scale of board impact" },
      { name: "duration", type: "number", note: "Rounds the effect persists" },
      { name: "affects", type: "enum", note: "all_players / active_player / specific_faction / board" },
      { name: "trigger_condition", type: "string", note: "What causes this event to fire" },
      { name: "reversible", type: "boolean", note: "Can players undo the effect?" },
      { name: "chained", type: "boolean", note: "This event draws another event after resolving?" },
    ],
    designTip:
      "Events should never feel arbitrary. The best events create decisions (respond now or ignore?), shift power temporarily, and give trailing players a path back. Avoid events that punish whoever is already winning.",
  },
  Resource: {
    color: "text-teal-400",
    border: "border-teal-500/30",
    bg: "bg-teal-500/5",
    badge: "bg-teal-500/20 text-teal-400 border-teal-500/30",
    hex: "#0d9488",
    icon: "💎",
    tagline: "Currency, materials, or consumables that fuel actions and purchases.",
    what: "Resources are the engine of your economy. Players collect, spend, and trade them to take actions, acquire components, and advance toward victory. The flow of resources should feel like a living system, not just a score counter.",
    ideas: [
      "Gold / Coin — Universal currency for purchasing",
      "Food / Supply — Upkeep cost per unit per round",
      "Wood / Stone — Construction material for buildings",
      "Mana / Energy — Fuel for spells or special abilities",
      "Influence — Social capital for political actions",
      "Research Points — Unlock technology or new abilities",
      "Trade Good — Commodity with variable exchange rates",
    ],
    properties: [
      { name: "quantity", type: "number", note: "Total supply across all players" },
      { name: "max_hold", type: "number", note: "Max a single player can hold at once" },
      { name: "per_turn_yield", type: "number", note: "Gained automatically each round" },
      { name: "tradeable", type: "boolean", note: "Can players exchange with each other?" },
      { name: "conversion_rate", type: "string", note: "Exchange ratio to other resources (e.g. 2:1)" },
      { name: "perishable", type: "boolean", note: "Lost if not spent by end of round?" },
    ],
    designTip:
      "A resource with no sink inflates until it's meaningless. For every resource, ensure there is at least one compelling way to spend it. Scarcity — not abundance — creates the interesting choices.",
  },
  Ability: {
    color: "text-pink-400",
    border: "border-pink-500/30",
    bg: "bg-pink-500/5",
    badge: "bg-pink-500/20 text-pink-400 border-pink-500/30",
    hex: "#db2777",
    icon: "✨",
    tagline: "Special powers, skills, or triggered effects tied to characters or factions.",
    what: "Abilities define what makes a character, card, or faction feel unique. A great ability creates a distinctive playstyle rather than just adding raw numbers. It answers: 'What can I do that others cannot?'",
    ideas: [
      "Passive Ability — Always-on stat modifier or rule exception",
      "Active Skill — Player chooses exactly when to activate",
      "Triggered Effect — Fires automatically when condition met",
      "Ultimate — Powerful effect with a long cooldown",
      "Reaction — Fires in response to another player's action",
      "Aura — Affects adjacent units or entities passively",
      "Combo Ability — Requires another card or action to unlock",
    ],
    properties: [
      { name: "cost", type: "number", note: "Resources or action points to activate" },
      { name: "cooldown", type: "number", note: "Rounds before can activate again" },
      { name: "trigger_type", type: "enum", note: "active / passive / triggered / reaction / aura" },
      { name: "target", type: "enum", note: "self / ally / enemy / all / location" },
      { name: "effect_type", type: "enum", note: "buff / debuff / damage / heal / draw / move / summon" },
      { name: "duration", type: "number", note: "Rounds effect lasts (0 = instant)" },
      { name: "range", type: "number", note: "Tiles / spaces the ability can reach" },
    ],
    designTip:
      "Abilities should have clear trade-offs. A free always-on ability with no cost isn't memorable. The restriction IS the design — 'you can do this amazing thing, but only when X' creates the stories players remember.",
  },
};

export const PROPERTY_GLOSSARY: GlossaryEntry[] = [
  {
    name: "cost",
    dataType: "number",
    appliesTo: ["Card", "Ability", "Resource", "Meeple"],
    description: "Resources or action points required to play, activate, or purchase this component.",
    rulesInteraction: "Referenced in spend rules: 'Pay {cost} gold to play this card.' Drives economy balance and limits per-turn burst power.",
    example: "cost: 3 — requires 3 gold to activate this ability.",
  },
  {
    name: "attack / power",
    dataType: "number",
    appliesTo: ["Card", "Meeple", "Faction", "Ability"],
    description: "The offensive stat used in combat — damage dealt when attacking another unit or player.",
    rulesInteraction: "Compared against the defender's defense stat. Often modified by terrain bonuses, status effects, or ability buffs from rules.",
    example: "attack: 5 — deals 5 damage before the defender's defense is applied.",
  },
  {
    name: "defense",
    dataType: "number",
    appliesTo: ["Card", "Meeple", "Tile", "Location", "Faction"],
    description: "Damage reduction or protection value. Subtracted from incoming attack before health loss is applied.",
    rulesInteraction: "Stacks with terrain: 'Effective defense = unit.defense + tile.defense_bonus.' Rules must specify whether defense is applied before or after special effects.",
    example: "defense: 2 — reduces all incoming damage by 2.",
  },
  {
    name: "health / hp",
    dataType: "number",
    appliesTo: ["Meeple", "Faction", "Card"],
    description: "Hit points before the component is removed, defeated, or destroyed.",
    rulesInteraction: "Depleted by attack damage, event severity, or ability effects. Restored by heal actions. Rules should address what happens when health reaches exactly 0 vs. goes negative.",
    example: "health: 10 — the unit is removed from the board when this reaches 0.",
  },
  {
    name: "movement",
    dataType: "number",
    appliesTo: ["Meeple", "Tile"],
    description: "Spaces or tiles a unit can traverse in a single move action.",
    rulesInteraction: "Modified by terrain movement_cost: 'A forest tile costs 2 movement to enter instead of 1.' Abilities and cards can extend or restrict this per turn.",
    example: "movement: 3 — unit may cross up to 3 standard (cost-1) tiles per action.",
  },
  {
    name: "range",
    dataType: "number",
    appliesTo: ["Card", "Ability", "Meeple"],
    description: "Tiles or spaces from which this component can target or affect other entities.",
    rulesInteraction: "Distance to target must be ≤ range. Rules must define whether terrain blocks line of sight and how distance is measured (Manhattan, Chebyshev, or path length).",
    example: "range: 2 — can target any unit within 2 tiles, regardless of walls.",
  },
  {
    name: "duration",
    dataType: "number",
    appliesTo: ["Ability", "Event", "Card"],
    description: "Number of rounds an effect persists before expiring automatically. 0 means instant (resolves this turn only).",
    rulesInteraction: "Decremented each round. Rules must specify exactly when it ticks (start vs. end of round) and what happens on expiry (the effect simply ends, or a new effect triggers).",
    example: "duration: 3 — the buff lasts for 3 rounds then fades without further action.",
  },
  {
    name: "cooldown",
    dataType: "number",
    appliesTo: ["Ability", "Card", "Die"],
    description: "Rounds that must pass before this ability or card can be activated again after use.",
    rulesInteraction: "Track with an exhausted marker or counter on the card. Rules must specify whether cooldown starts counting immediately or on the following round.",
    example: "cooldown: 2 — after activating, must wait 2 full rounds before using again.",
  },
  {
    name: "rarity",
    dataType: "enum",
    appliesTo: ["Card", "Token", "Resource"],
    description: "Distribution tier — how frequently this component appears. Drives perceived value and draft/deck strategy.",
    rulesInteraction: "Often determines inclusion limits: 'You may have at most 1 legendary card per deck.' Rarer components are expected to be proportionally more impactful.",
    example: "rarity: legendary — only 1 copy exists in the entire game box.",
  },
  {
    name: "quantity",
    dataType: "number",
    appliesTo: ["Token", "Resource", "Card"],
    description: "Total copies of this component available across the entire game. A hard scarcity ceiling.",
    rulesInteraction: "When the supply is depleted, no more can be gained. Rules must address what happens when someone tries to take more than is available.",
    example: "quantity: 24 — only 24 gold tokens exist. Once taken, others must wait for someone to spend.",
  },
  {
    name: "terrain_type",
    dataType: "enum",
    appliesTo: ["Tile", "Location"],
    description: "The surface or environmental type, affecting movement cost, combat bonuses, and available actions.",
    rulesInteraction: "Cross-referenced in movement rules ('entering forest costs 2 movement') and combat rules ('mountains grant +1 defense to defenders').",
    example: "terrain_type: mountain — costs 2 movement to enter, grants +2 defense to occupants.",
  },
  {
    name: "resource_yield",
    dataType: "number",
    appliesTo: ["Location", "Tile", "Resource"],
    description: "Resources produced per turn when a player occupies or controls this component.",
    rulesInteraction: "Triggers during the income phase: 'Each player collects resource_yield from each controlled location.' Multiple locations stack.",
    example: "resource_yield: 2 — controlling this location produces 2 gold per round.",
  },
  {
    name: "capacity",
    dataType: "number",
    appliesTo: ["Location", "Deck", "Board"],
    description: "Maximum number of units, tokens, or cards that can occupy this component simultaneously.",
    rulesInteraction: "Enforced during placement: 'You may not move a unit into a location at its capacity.' Creates natural chokepoints and bottleneck tension.",
    example: "capacity: 3 — no more than 3 units from any combination of players may occupy this location.",
  },
  {
    name: "connected_to",
    dataType: "string",
    appliesTo: ["Location", "Tile"],
    description: "Comma-separated list of adjacent locations reachable in a single move without passing through other named locations.",
    rulesInteraction: "Defines the movement graph. Rules must specify whether adjacency is undirected (bidirectional) or directed (one-way passage only).",
    example: "connected_to: 'Dark Forest, Mountain Pass' — units may move freely to either neighbor.",
  },
  {
    name: "trigger_condition",
    dataType: "string",
    appliesTo: ["Event", "Ability", "Card"],
    description: "The game-state condition that must be true for this effect to activate automatically.",
    rulesInteraction: "Evaluated at specific timing windows defined in the rules (start of round, on attack, when a threshold is crossed). Multiple triggers on the same timing window resolve in declared order.",
    example: "trigger_condition: 'when any player reaches 10 VP' — fires the event at that scoring milestone.",
  },
  {
    name: "frequency",
    dataType: "enum",
    appliesTo: ["Event"],
    description: "How often this event occurs: once (single-use), rare (~25% per round), uncommon (~50%), or every_round.",
    rulesInteraction: "Determines event deck composition. A 'rare' event would appear 1–2 times in a 60-card deck. Higher frequency events should have lower severity to avoid oppressive patterns.",
    example: "frequency: rare — drawn roughly once every 4 rounds on average.",
  },
  {
    name: "severity",
    dataType: "number",
    appliesTo: ["Event"],
    description: "1–10 scale of how impactful an event is on the board state or player resources.",
    rulesInteraction: "High-severity events may trigger mandatory response rules: 'If severity ≥ 8, all players must sacrifice 1 unit immediately.' Low-severity events are background noise.",
    example: "severity: 7 — a major disruption; all players lose 2 resources immediately.",
  },
  {
    name: "diplomatic_stance",
    dataType: "enum",
    appliesTo: ["Faction"],
    description: "The faction's default relationship posture: aggressive, neutral, peaceful, or isolationist.",
    rulesInteraction: "Determines NPC/AI behavior. Affects trade rates, attack thresholds, and alliance availability as defined in faction interaction rules.",
    example: "diplomatic_stance: aggressive — this faction attacks adjacent players whenever able each round.",
  },
  {
    name: "influence",
    dataType: "number",
    appliesTo: ["Faction", "Location", "Resource"],
    description: "Social, political, or cultural power used for non-military control, negotiation, and special actions.",
    rulesInteraction: "Compared in political resolution: 'Player with highest influence wins the election.' May decay if not actively maintained through actions or events.",
    example: "influence: 5 — faction starts with moderate political standing in the council.",
  },
  {
    name: "tradeable",
    dataType: "boolean",
    appliesTo: ["Resource", "Token", "Card"],
    description: "Whether players may freely exchange this component with each other during designated trading phases.",
    rulesInteraction: "Non-tradeable resources prevent snowball trading. Rules must define when trading windows open and whether trades require both parties to agree.",
    example: "tradeable: true — players may negotiate and freely exchange this resource on their turn.",
  },
  {
    name: "effect_type",
    dataType: "enum",
    appliesTo: ["Card", "Ability"],
    description: "The category of gameplay effect produced: buff, debuff, damage, heal, draw, discard, move, or summon.",
    rulesInteraction: "Used to limit combinations: 'You may play at most 1 damage card per turn.' Also drives UI categorization and priority ordering when effects resolve simultaneously.",
    example: "effect_type: buff — temporarily increases an ally's attack or defense for the duration.",
  },
  {
    name: "victory_points",
    dataType: "number",
    appliesTo: ["Token", "Location", "Card", "Faction"],
    description: "Score value contributed to a player's final score when end-game conditions are triggered.",
    rulesInteraction: "Summed in the scoring phase. May be conditional: 'Score 1 VP per unit in your territory.' The scoring phase rules must enumerate every VP source to prevent disputes.",
    example: "victory_points: 3 — controlling this location at game end is worth 3 points.",
  },
  {
    name: "per_player",
    dataType: "boolean",
    appliesTo: ["Token", "Board", "Meeple"],
    description: "Whether each player has their own independent copy (true) or all players share one pool (false).",
    rulesInteraction: "Shared components create indirect conflict and contention. Per-player components simplify bookkeeping but increase component count and cost.",
    example: "per_player: true — each player has their own token supply; players cannot see each other's counts.",
  },
  {
    name: "defense_bonus",
    dataType: "number",
    appliesTo: ["Location", "Tile"],
    description: "Combat modifier added to units occupying this space when defending against attacks.",
    rulesInteraction: "Added to the unit's base defense during combat resolution: 'Effective defense = unit.defense + tile.defense_bonus.' Rules should cap maximum effective defense.",
    example: "defense_bonus: 2 — all units occupying this tile gain +2 defense against any attack.",
  },
  {
    name: "perishable",
    dataType: "boolean",
    appliesTo: ["Resource", "Token"],
    description: "Whether unused quantities of this resource are discarded at the end of the round rather than carried over.",
    rulesInteraction: "Creates urgent spend pressure. Rules must define exactly when the discard check occurs (end of active player's turn vs. end of full round) and whether players can convert perishables to non-perishables.",
    example: "perishable: true — unspent food tokens are discarded at end of round.",
  },
  {
    name: "shared",
    dataType: "boolean",
    appliesTo: ["Deck", "Board"],
    description: "Whether all players draw from or interact with the same single component, vs. each having their own private version.",
    rulesInteraction: "Shared decks create race dynamics (take the good cards before others). Private decks isolate strategy. Rules must specify interaction rules when shared components become contested.",
    example: "shared: true — all players draw from the same encounter deck; its depletion affects everyone.",
  },
];
