import { useState, useEffect, useCallback } from "react";
import { useListChangelog } from "@workspace/api-client-react";
import {
  Download, FileText, FileJson, Package, History, Mail, Layout,
  Sparkles, Loader2, ExternalLink, RefreshCw, Trash2, BookOpen, Presentation, Palette, FileBadge,
} from "lucide-react";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";

const FORMATS = [
  { kind: "tts-json", icon: FileJson, title: "Tabletop Simulator JSON", desc: "Drop this into Tabletop Simulator to import your prototype." },
  { kind: "rulebook-md", icon: FileText, title: "Rulebook (Markdown)", desc: "AI-formatted rulebook ready to publish." },
  { kind: "kickstarter", icon: Layout, title: "Kickstarter copy", desc: "Pitch-ready campaign description." },
  { kind: "sell-sheet", icon: Package, title: "Sell sheet", desc: "Single-page sales overview for retailers and publishers." },
  { kind: "press-kit", icon: Mail, title: "Press kit", desc: "Talking points and media assets for outreach." },
] as const;

const GAMMA_FORMATS = [
  { kind: "rulebook", icon: BookOpen, title: "Designed rulebook (PDF)", desc: "Multi-page rulebook with hierarchical sections, illustrations, and styled layout — generated by Gamma." },
  { kind: "pitch-deck", icon: Presentation, title: "Kickstarter pitch deck", desc: "16:9 backer-ready pitch deck with hero artwork and pledge sections." },
  { kind: "onepager", icon: FileBadge, title: "Publisher one-pager", desc: "Single-page sell sheet with art, USPs, and at-a-glance stats." },
  { kind: "art-bible", icon: Palette, title: "Art bible", desc: "Visual style guide with concept art for box, characters, and components." },
] as const;

type GammaKind = typeof GAMMA_FORMATS[number]["kind"];

interface KickstarterAsset {
  id: number;
  projectId: number;
  kind: string;
  title: string;
  status: "pending" | "processing" | "completed" | "failed";
  generationId: string | null;
  gammaUrl: string | null;
  pdfUrl: string | null;
  pptxUrl: string | null;
  errorMessage: string | null;
  createdAt: string;
  completedAt: string | null;
}

function apiBase() {
  return import.meta.env.BASE_URL.replace(/\/$/, "");
}

export function Exports({ projectId }: { projectId: number }) {
  const { toast } = useToast();
  const { data: changelog, isLoading } = useListChangelog(projectId);
  const [downloading, setDownloading] = useState<string | null>(null);

  const [gammaAssets, setGammaAssets] = useState<KickstarterAsset[]>([]);
  const [gammaLoading, setGammaLoading] = useState(true);
  const [generating, setGenerating] = useState<GammaKind | null>(null);

  const loadGamma = useCallback(async () => {
    try {
      const res = await fetch(`${apiBase()}/api/projects/${projectId}/kickstarter`, { credentials: "include" });
      if (res.ok) {
        const rows = (await res.json()) as KickstarterAsset[];
        setGammaAssets(rows);
      }
    } finally {
      setGammaLoading(false);
    }
  }, [projectId]);

  useEffect(() => { loadGamma(); }, [loadGamma]);

  // Auto-poll any in-flight generations every 6 seconds.
  useEffect(() => {
    const inFlight = gammaAssets.filter(a => a.status === "pending" || a.status === "processing");
    if (inFlight.length === 0) return;
    const id = setInterval(async () => {
      await Promise.all(inFlight.map(async (a) => {
        try {
          const r = await fetch(`${apiBase()}/api/projects/${projectId}/kickstarter/${a.id}/refresh`, {
            method: "POST",
            credentials: "include",
          });
          if (r.ok) {
            const updated = (await r.json()) as KickstarterAsset;
            setGammaAssets(prev => prev.map(x => x.id === updated.id ? updated : x));
          }
        } catch { /* ignore single-poll failure */ }
      }));
    }, 6000);
    return () => clearInterval(id);
  }, [gammaAssets, projectId]);

  const generateGamma = async (kind: GammaKind) => {
    setGenerating(kind);
    try {
      const res = await fetch(`${apiBase()}/api/projects/${projectId}/kickstarter/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ kind }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error || "generation failed");
      setGammaAssets(prev => [data as KickstarterAsset, ...prev]);
      toast({ title: "Gamma is generating", description: "We'll show the result here when it's ready." });
    } catch (e) {
      toast({ title: "Could not start generation", description: e instanceof Error ? e.message : String(e), variant: "destructive" });
    } finally {
      setGenerating(null);
    }
  };

  const refreshAsset = async (id: number) => {
    try {
      const r = await fetch(`${apiBase()}/api/projects/${projectId}/kickstarter/${id}/refresh`, {
        method: "POST",
        credentials: "include",
      });
      const data = await r.json().catch(() => null);
      if (r.ok && data) {
        setGammaAssets(prev => prev.map(x => x.id === (data as KickstarterAsset).id ? data as KickstarterAsset : x));
      } else {
        toast({
          title: "Refresh failed",
          description: (data && (data as { error?: string }).error) || `HTTP ${r.status}`,
          variant: "destructive",
        });
      }
    } catch (e) {
      toast({ title: "Refresh failed", description: e instanceof Error ? e.message : String(e), variant: "destructive" });
    }
  };

  const deleteAsset = async (id: number) => {
    try {
      const r = await fetch(`${apiBase()}/api/projects/${projectId}/kickstarter/${id}`, {
        method: "DELETE",
        credentials: "include",
      });
      if (!r.ok) {
        const data = await r.json().catch(() => null);
        toast({
          title: "Delete failed",
          description: (data && (data as { error?: string }).error) || `HTTP ${r.status}`,
          variant: "destructive",
        });
        return;
      }
      setGammaAssets(prev => prev.filter(x => x.id !== id));
    } catch (e) {
      toast({ title: "Delete failed", description: e instanceof Error ? e.message : String(e), variant: "destructive" });
    }
  };

  const downloadFile = async (kind: typeof FORMATS[number]["kind"]) => {
    setDownloading(kind);
    try {
      const res = await fetch(`${apiBase()}/api/projects/${projectId}/export/${kind}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: "{}",
      });
      if (!res.ok) throw new Error("download failed");
      const data: { kind: string; content: string; contentType: string; filename: string } = await res.json();
      const blob = new Blob([data.content], { type: data.contentType });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = data.filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      toast({ title: "Exported", description: `${data.filename} downloaded.` });
    } catch { toast({ title: "Export failed", variant: "destructive" }); }
    finally { setDownloading(null); }
  };

  return (
    <div className="space-y-6 max-w-5xl">
      <div>
        <h2 className="text-2xl font-bold flex items-center gap-2"><Download className="h-6 w-6 text-primary" /> Export</h2>
        <p className="text-muted-foreground text-sm mt-1">Generate downloadable artifacts for play, pitching, and publishing.</p>
      </div>

      <Card className="bg-card border-card-border">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" /> Designed PDFs &amp; decks
            <Badge variant="secondary" className="text-[10px]">Gamma</Badge>
          </CardTitle>
          <CardDescription>
            Generate fully designed PDFs and presentations with AI-generated artwork using Gamma. Each generation takes 30–90 seconds.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {GAMMA_FORMATS.map(f => {
              const Icon = f.icon;
              return (
                <div key={f.kind} className="border border-border rounded-lg p-4 bg-background/50">
                  <div className="flex items-start gap-3 mb-2">
                    <Icon className="h-5 w-5 text-primary mt-0.5" />
                    <div>
                      <div className="font-medium text-sm">{f.title}</div>
                      <div className="text-xs text-muted-foreground mt-0.5">{f.desc}</div>
                    </div>
                  </div>
                  <Button
                    size="sm"
                    onClick={() => generateGamma(f.kind)}
                    disabled={generating === f.kind}
                    className="gap-2 w-full"
                    data-testid={`button-generate-gamma-${f.kind}`}
                  >
                    {generating === f.kind
                      ? <><Loader2 className="h-3 w-3 animate-spin" /> Starting…</>
                      : <><Sparkles className="h-3 w-3" /> Generate with Gamma</>}
                  </Button>
                </div>
              );
            })}
          </div>

          <div className="border-t border-border pt-4">
            <div className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-3">Generated assets</div>
            {gammaLoading ? (
              <div className="space-y-2">{[1,2].map(i => <Skeleton key={i} className="h-16" />)}</div>
            ) : gammaAssets.length === 0 ? (
              <div className="text-sm text-muted-foreground text-center py-4">
                No Gamma assets yet. Click any "Generate with Gamma" button above.
              </div>
            ) : (
              <div className="space-y-2">
                {gammaAssets.map(a => (
                  <div key={a.id} className="flex items-center gap-3 p-3 border border-border rounded-lg bg-background/30" data-testid={`gamma-asset-${a.id}`}>
                    <div className="flex-1 min-w-0">
                      <div className="text-sm font-medium truncate">{a.title}</div>
                      <div className="text-[10px] text-muted-foreground mt-0.5 flex items-center gap-2">
                        <Badge
                          variant={a.status === "completed" ? "default" : a.status === "failed" ? "destructive" : "secondary"}
                          className="text-[9px] px-1.5 py-0"
                        >
                          {a.status}
                        </Badge>
                        <span>{format(new Date(a.createdAt), "MMM d, h:mm a")}</span>
                        {a.errorMessage && <span className="text-destructive truncate">· {a.errorMessage}</span>}
                      </div>
                    </div>
                    <div className="flex items-center gap-1">
                      {a.gammaUrl && (
                        <a href={a.gammaUrl} target="_blank" rel="noopener noreferrer">
                          <Button size="sm" variant="ghost" className="gap-1 h-8">
                            <ExternalLink className="h-3 w-3" /> Open in Gamma
                          </Button>
                        </a>
                      )}
                      {a.pdfUrl && (
                        <a href={a.pdfUrl} target="_blank" rel="noopener noreferrer">
                          <Button size="sm" variant="default" className="gap-1 h-8">
                            <Download className="h-3 w-3" /> PDF
                          </Button>
                        </a>
                      )}
                      {a.pptxUrl && (
                        <a href={a.pptxUrl} target="_blank" rel="noopener noreferrer">
                          <Button size="sm" variant="default" className="gap-1 h-8">
                            <Download className="h-3 w-3" /> PPTX
                          </Button>
                        </a>
                      )}
                      {(a.status === "pending" || a.status === "processing") && (
                        <Button size="icon" variant="ghost" className="h-8 w-8" onClick={() => refreshAsset(a.id)}>
                          <RefreshCw className="h-3 w-3" />
                        </Button>
                      )}
                      <Button size="icon" variant="ghost" className="h-8 w-8 text-muted-foreground hover:text-destructive" onClick={() => deleteAsset(a.id)}>
                        <Trash2 className="h-3 w-3" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      <div>
        <h3 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground mb-3">Quick text exports</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {FORMATS.map(f => {
            const Icon = f.icon;
            return (
              <Card key={f.kind} className="bg-card border-card-border">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2"><Icon className="h-5 w-5 text-primary" /> {f.title}</CardTitle>
                  <CardDescription>{f.desc}</CardDescription>
                </CardHeader>
                <CardContent>
                  <Button onClick={() => downloadFile(f.kind)} disabled={downloading === f.kind} className="gap-2">
                    <Download className="h-4 w-4" /> {downloading === f.kind ? "Generating..." : "Generate & download"}
                  </Button>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2"><History className="h-5 w-5" /> Changelog</CardTitle>
          <CardDescription>Auto-tracked design milestones and AI changes.</CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-3">{[1,2,3].map(i => <Skeleton key={i} className="h-12" />)}</div>
          ) : !changelog?.length ? (
            <div className="text-sm text-muted-foreground text-center py-6">No changes recorded yet.</div>
          ) : (
            <div className="space-y-3">
              {changelog.map(c => (
                <div key={c.id} className="border-l-2 border-primary/40 pl-4 py-1">
                  <div className="text-sm font-medium">{c.summary}</div>
                  <div className="text-xs text-muted-foreground">{format(new Date(c.createdAt), "MMM d, yyyy h:mm a")} • {c.action}</div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
